[package]
name = "ring-module-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
cargo_toml = "0.22.1"
tracing = "0.1.41"

ring-core-file = { path = "../ring-core-file" }
ring-core-modules = { path = "../ring-core-modules" }
ring-core-units = { path = "../ring-core-units" }
ring-module-toml = { path = "../ring-module-toml" }