[package]
name = "ring-cli"
version = "0.4.0"
edition = "2021"

[features]
default = [
    "ring-core/javascript",
    "ring-core/json",
    "ring-core/ring",
    "ring-core/rust",
    "ring-core/shell",
    "ring-core/toml",
    "ring-core/typescript",
    "ring-core/yaml",
    "ring-core/lscolors",
]

[dependencies]
anyhow = "1.0.98"
bytesize = "2.0.1"
clap = "4.5.37"
crossterm = "0.29.0"
itertools = "0.14.0"
lscolors = { version = "0.20.0", default-features = false, features = ["crossterm"] }
sentry = { version = "0.41.0", features = ["anyhow", "tracing"] }
serde_json = "1.0.140"
sysinfo = "0.35.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

ring-cli-list = { path = "../ring-cli-list" }
ring-cli-tree = { path = "../ring-cli-tree" }
ring-core = { path = "../ring-core", features = ["crossterm"] }
