component_management:
  default_rules:
    statuses:
      - type: project
        target: auto

      - type: patch
        target: auto

  individual_components:
    - component_id: cli
      name: cli
      paths:
        - crates/ring-cli/**
        - crates/ring-cli-table/**

    - component_id: core
      name: core
      paths:
        - crates/ring-core/**

    - component_id: modules
      name: modules
      paths:
        - crates/ring-web/**

    - component_id: utils
      name: utils
      paths:
        - crates/ring-color/**
        - crates/ring-tag/**
