component_management:
  default_rules:
    statuses:
      - type: project
        target: auto

      - type: patch
        target: auto

  individual_components:
    - component_id: crate-ring-cli
      name: cli
      paths:
        - crates/ring-cli/**

    - component_id: crate-ring-tag
      name: tag
      paths:
        - crates/ring-tag/**