[package]
name = "ring-tag"
version = "0.1.0"
edition = "2021"

[features]
crossterm = ["ring-color/crossterm", "dep:crossterm", "dep:supports-color"]
owo-colors = ["ring-color/owo-colors", "dep:owo-colors", "dep:supports-color"]

[dependencies]
rgb = "0.8.50"

crossterm = { version = "0.28.1", optional = true }
owo-colors = { version = "4.1.0", optional = true }
supports-color = { version = "3.0.2", optional = true }

ring-color = { path = "../ring-color" }

[dev-dependencies]
mockall = "0.13.1"