[package]
name = "ring-module-ring"
version = "0.1.0"
edition = "2024"

[dependencies]
rgb = { version = "0.8.50", features = ["serde"] }
sysinfo = "0.36.0"
tracing = "0.1.41"

ring-core-modules = { path = "../ring-core-modules" }
ring-core-tasks = { path = "../ring-core-tasks" }
ring-core-units = { path = "../ring-core-units" }