[package]
name = "ring-web"
version = "0.1.0"
edition = "2021"

[features]
owo-colors = ["ring-color/owo-colors", "ring-tag/owo-colors", "dep:owo-colors"]

[dependencies]
anyhow = "1.0.93"
rgb = "0.8.50"
tracing = "0.1.41"
semver = { version = "1.0.23", features = ["serde"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"

owo-colors = { version = "4.1.0", optional = true }

ring-color = { path = "../ring-color" }
ring-code-unit = { path = "../ring-code-unit" }
ring-tag = { path = "../ring-tag" }
