[package]
name = "ring-module-javascript"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
rgb = { version = "0.8.50", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sysinfo = "0.36.0"
tracing = "0.1.41"

ring-core-content = { path = "../ring-core-content" }
ring-core-fs = { path = "../ring-core-fs" }
ring-core-modules = { path = "../ring-core-modules" }
ring-core-tasks = { path = "../ring-core-tasks" }
ring-core-units = { path = "../ring-core-units" }
ring-module-json = { path = "../ring-module-json" }
ring-module-yaml = { path = "../ring-module-yaml" }