[package]
name = "ring-files"
version = "0.2.1"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
tracing = "0.1.40"

ring-traits = { path = "../ring-traits" }
ring-utils = { path = "../ring-utils" }