[package]
name = "ring-js-project"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tracing = "0.1.40"
