[package]
name = "ring-js-project"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
glob = "0.3.1"
semver = "1.0.23"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tracing = "0.1.40"
log = "0.4.21"

ring-project = { path = "../ring-project" }