name: CI

on:
  push:
    branches: [ 'latest' ]

  pull_request:
    branches: [ 'latest' ]

concurrency:
  group: rust-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install SARIF utils
        run: cargo install clippy-sarif sarif-fmt

      - name: Run clippy
        run: cargo clippy --all-targets --all-features --message-format=json | clippy-sarif | tee results.sarif | sarif-fmt

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          wait-for-processing: true

  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
          cache: yarn

      - name: Install js dependencies
        run: yarn install --immutable

      - name: ESLint
        continue-on-error: true
        run: yarn lint -f @microsoft/sarif -o eslint-results.sarif

      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true

  unit-tests:
    name: Unit tests on ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux-amd64
            runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu

          - name: win-amd64
            runner: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
          targets: ${{ matrix.target }}

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo --locked llvm-cov --lcov --output-path codecov-unit.json nextest --workspace --all-features --profile ci --config-file .github/nextest.toml

      - name: Upload coverage to Codecov
        if: ${{ !startsWith(github.head_ref, 'dependabot/') && !startsWith(github.head_ref, 'renovate/') }}
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: codecov-unit.json
          flags: unit,${{ matrix.name }}
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() && !startsWith(github.head_ref, 'dependabot/') && !startsWith(github.head_ref, 'renovate/') }}
        uses: codecov/test-results-action@v1
        with:
          files: target/nextest/ci/junit.xml
          flags: unit,${{ matrix.name }}
          token: ${{ secrets.CODECOV_TOKEN }}

  docs-tests:
    name: Documentation tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Test docs
        run: cargo --locked llvm-cov --lcov --output-path codecov-docs.json test --doc

      - name: Upload coverage to Codecov
        if: ${{ !startsWith(github.head_ref, 'dependabot/') && !startsWith(github.head_ref, 'renovate/') }}
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          files: codecov-docs.json
          flags: docs
          token: ${{ secrets.CODECOV_TOKEN }}
